README.md

Just highlight that the code is online

Slight text update

---

src/main/java/com/xceptance/xlt/mastercontroller/Main.java
src/test/java/com/xceptance/xlt/mastercontroller/AdditionalPropertiesConfigFileTest.java

- made methods of master controller Main non-static and protected so we can inherit from Main and overwrite these methods as needed
- moved any System.exit() to the new run() method so the JVM does not quit by accident when subclasses call any of the other methods
- adjusted test case

Allow for subclassing of master controller Main

---

src/main/java/com/xceptance/xlt/engine/resultbrowser/DomUtils.java
src/test/java/com/xceptance/xlt/engine/resultbrowser/DomUtilsTest.java

Failed to dump SVG correctly

---

doc/xltdoc/_config.yml
doc/xltdoc/_includes/breadcrumb.html
doc/xltdoc/css/xltdoc.less
doc/xltdoc/getting-started/01-test-automation.textile
doc/xltdoc/release-notes/index.html
doc/xltdoc/user-manual/02-install.textile
doc/xltdoc/user-manual/03-scriptdeveloper.textile
doc/xltdoc/user-manual/index.html

Make the old documentation legacy. 
Links to #90

Make documentation legacy and point to new

---

src/main/java/com/xceptance/xlt/gce/GceAdminUtils.java
src/main/java/com/xceptance/xlt/gce/MachineInfo.java

* fall back to a private IP if an instance does not have a public IP
* be more defensive in this area as all values returned by Google might be null

#100: NPE when listing or deleting machine instances with gce_admin

---

pom.xml

#102: Result browser broken when running test cases with Java 16

---

build.properties

download Jenkins plugin from Maven Central

#112: Ship Jenkins plugin v2.x.x with XLT

---

xlt-timerrecorder-chrome/src/background.js

added flag to also get "extra" request/response headers such as Cookie and Set-Cookie

#110: Cookie headers not recorded with Chrome

---

src/main/java/com/xceptance/xlt/agentcontroller/AgentImpl.java

when killing an agent kill it forcefully

#148: Forcefully kill hanging agent processes when aborting a load test

---

src/main/java/com/xceptance/xlt/agentcontroller/AgentControllerImpl.java
src/main/java/com/xceptance/xlt/mastercontroller/MasterController.java

Use JupIOFactory to achieve similar parsing results as with java.util.Properties.

#144: No result download possible for a certain test suite configuration

---

ant-scripts/test.xml
src/main/java/com/xceptance/xlt/engine/htmlunit/okhttp3/OkHttp3WebConnection.java
src/test/java/com/xceptance/xlt/engine/OkHttpRequestBodyEncodingTest.java

Create a binary OkHttp request body for presumably binary content.

#138: Binary request bodies mixed up for OkHttp-based web connection

---

pom.xml

update ant to latest to get rid of security issues

Update Ant dependency

---

pom.xml
src/main/java/com/xceptance/xlt/engine/dns/DnsJavaHostNameResolver.java

- updated dnsjava to version 3.5.0
- fixed a deprecation warning in DnsJavaHostNameResolver

#24: Update to dnsjava 3.x

---

samples/testsuite-performance/config/project.properties
samples/testsuite-posters/config/project.properties
samples/testsuite-showcases/config/project.properties
samples/testsuite-template/config/project.properties
samples/testsuite-xlt/config/project.properties
src/main/java/com/xceptance/xlt/clientperformance/PerformanceDataTransformator.java
src/main/java/com/xceptance/xlt/engine/XltHttpWebConnection.java
src/main/java/com/xceptance/xlt/report/ReportGeneratorConfiguration.java
src/main/java/com/xceptance/xlt/report/mergerules/HttpMethodRequestFilter.java
src/main/java/com/xceptance/xlt/report/mergerules/RequestProcessingRule.java
src/test/java/com/xceptance/xlt/engine/clientperformance/PerformanceDataTransformatorTest.java
src/test/java/com/xceptance/xlt/report/mergerules/RequestProcessingRuleTest.java

- added a new request filter type to allow request processing by HTTP method
- adjusted/extended unit tests
- added new filter pattern to project.properties

#73: Extend Merge Rules by Method

---

pom.xml

Ensure the optional dependency jna-platform of dnsjava is present.

#220: UnknownHostException with dnsjava-based host name resolver

---

src/main/java/com/xceptance/xlt/engine/XltWebClient.java

Don't brute-force copy response content

---

src/main/java/com/xceptance/xlt/engine/resultbrowser/RequestHistory.java

Only create the page for the request history when it is needed

---

pom.xml

Pin guava to highest version used.

#246: Guava version clash

---

resultbrowser/src/css/default.css
resultbrowser/src/js/resultbrowser.js

- Ensure request body is shown again.
- Fixed a design glitch when showing request body/post parameters.

#258: Request body no longer shown on the Request Information tab

---

samples/app-server/webapps/testpages/redirect/redirect.jsp
samples/testsuite-xlt/src/test/com/xceptance/xlt/engine/webdriver/RedirectTest.java
xlt-timerrecorder/background.js

- determine the correct request method for redirected requests and record that one
- added a test case to create certain redirect scenarios for verification purposes

#263: Firefox timer recorder: Wrong request method recorded

---

resultbrowser/src/js/resultbrowser.js

- also show redirects with status code 303, 307, and 308 in gray

#265: Some redirects not shown dimmed in the result browser

---

pom.xml

- reintroduced xalan
Closes #289

#289: Report generator fails with XSL error

---

src/main/java/com/xceptance/xlt/agentcontroller/AgentManagerImpl.java

Verify agent is up and running upon its start in `AgentManagerImpl` and throw exception otherwise (no agent status available within 5s or its error exit code is greater than 0).
Fixes #303

GH #303: Detect premature termination of agent process upon start of load test

---

README.md

Adds IDE development setup steps to README.
Closes #310

#310: instruction how to fix module dependency issue

---

build.xml
config/ec2_admin.properties
src/main/java/com/xceptance/xlt/ec2/AbstractEC2Client.java
src/main/java/com/xceptance/xlt/ec2/AwsConfiguration.java
src/main/java/com/xceptance/xlt/ec2/Main.java

Changes:
- removed fetch of pricing data when building XLT
- dropped pricing data URL configuration from AWS configuration
- removed parsing and handling of pricing information
Closes #352

GH #352: Drop pricing information from ec2_admin

---

config/testreport/css/default.css

fixed clear button overlapping the search bar text and changed cursor to pointer on hover over the button

380 x in reports filter fields overlaps field text

---

src/main/java/com/xceptance/xlt/agentcontroller/AgentManagerImpl.java

Don't error out when no status arrived within 5s but agent is still running.
Closes #385

GH #385: Failed to start load test using XLT 7

---

xlt-timerrecorder-chrome/src/background.js
xlt-timerrecorder-chrome/src/manifest.json

This reverts commit ce270b6314eaa7d73a72cee616ebf99118ad9246.

#391: Revert to the old timer recorder plugin for Chrome

---

resultbrowser/src/css/default.css
resultbrowser/src/css/json-tree.css
resultbrowser/src/css/json-viewer.css
resultbrowser/src/index.html
resultbrowser/src/js/json-tree.js
resultbrowser/src/js/json-viewer.js
resultbrowser/src/js/resultbrowser.js

- turned JSON tree view into a Web component
- extracted inline JSON viewer stuff into another Web component
- added a new tab "Request Body (JSON)" with an own JSON viewer instance
- did the needed adjustments to make it work again

#399: Viewer for JSON request bodies

---

config/xsl/diffreport/actions.xsl
config/xsl/diffreport/custom-timers.xsl
config/xsl/diffreport/index.xsl
config/xsl/diffreport/page-load-timings.xsl
config/xsl/diffreport/requests.xsl
config/xsl/diffreport/text/descriptions.xsl
config/xsl/diffreport/transactions.xsl
config/xsl/diffreport/util/timer-row.xsl
config/xsl/diffreport/util/timer-section.xsl
config/xsl/diffreport/util/timer-table.xsl
config/xsl/loadreport/util/timer-row.xsl
config/xsl/loadreport/util/timer-section.xsl
config/xsl/loadreport/util/timer-summary-row.xsl
config/xsl/loadreport/util/timer-table.xsl
src/main/java/com/xceptance/xlt/report/diffreport/DiffReportGeneratorConfiguration.java

Not sure what will happen if input reports are not using the same Pxx (usually 50/95/99/99.9), I will check this.

429 additional report metrics

---

resultbrowser/src/css/default.css
resultbrowser/src/index.html
resultbrowser/src/js/resultbrowser.js

First version, let's start with this and add more when needed. 
So far: 
* bigger font in menu
* column layout in mobile/portrait mode
* filter menu made usable on mobile (full screen overlay)
* navigation can be expanded/hidden on mobile in portrait mode
* realbrowser action screenshots are sized to 100% screen width per default, zoomable

465 responsive result browser

---

samples/app-server/start.ini
samples/testsuite-performance/config/default.properties
samples/testsuite-posters/config/default.properties
samples/testsuite-showcases/config/default.properties
samples/testsuite-template/config/default.properties
samples/testsuite-xlt/config/default.properties
src/main/java/com/xceptance/xlt/engine/XltWebClient.java
src/main/java/org/htmlunit/WebClientOptions.java

- make key/trust store configurable
- load key/trust stores on first use only and cache them for subsequent uses

#497: Make mTLS more convenient to use

---

resultbrowser/package-lock.json
resultbrowser/package.json

- updated parcel and other direct dependencies to latest
- recreated package-lock.json

#517: Update parcel

---

pom.xml

https://github.com/jfree/jfreechart/releases/tag/v1.5.5

Security upgrade JFreeChart

---

config/testreport/js/xlt.js

Reverts Xceptance/XLT#552
PR merged too early (by PR author :grin:  )

Revert "#551: Fixed hashupdate loop when clicking on sorting headers multiple…"

---

config/ec2_admin.properties
pom.xml
src/main/java/com/xceptance/xlt/ec2/AbstractEC2Client.java
src/main/java/com/xceptance/xlt/ec2/AwsConfiguration.java
src/main/java/com/xceptance/xlt/ec2/MachineInfo.java
src/main/java/com/xceptance/xlt/ec2/Main.java

See https://github.com/Xceptance/XLT/issues/540

#540 Update AWS SDK to version 2.27.21

---

config/ec2_admin.properties
src/main/java/com/xceptance/xlt/ec2/AbstractEC2Client.java
src/main/java/com/xceptance/xlt/ec2/AwsConfiguration.java

See:
- https://github.com/Xceptance/XLT/issues/557
- https://github.com/Xceptance/XLT/issues/558

#557 #558: ec2_admin: support temporary and globally stored credentials

---

pom.xml
src/main/java/com/xceptance/xlt/mastercontroller/MasterControllerMain.java

- updated some 3rd-party libs
- resolved ambiguities introduced by the new version of commons-cli

#578: Update 3rd-party libs

---

src/main/java/com/xceptance/common/util/AbsoluteOrRelativeNumber.java
src/main/java/com/xceptance/common/util/NumberUtils.java
src/main/java/com/xceptance/common/util/ParseUtils.java
src/main/java/com/xceptance/xlt/mastercontroller/AbstractLoadFunctionParser.java
src/main/java/com/xceptance/xlt/mastercontroller/DoubleValueLoadFunctionParser.java
src/main/java/com/xceptance/xlt/mastercontroller/LoadFunctionUtils.java
src/main/java/com/xceptance/xlt/mastercontroller/TestLoadProfileConfiguration.java
src/test/java/com/xceptance/common/util/NumberUtilsTest.java
src/test/java/com/xceptance/common/util/ParseUtilsTest.java
src/test/java/com/xceptance/xlt/mastercontroller/DoubleValueLoadFunctionParserTest.java
src/test/java/com/xceptance/xlt/mastercontroller/IntValueLoadFunctionParserTest.java
src/test/java/com/xceptance/xlt/mastercontroller/LoadFunctionUtilsTest.java

See: https://github.com/Xceptance/XLT/issues/570

#570 Allow relative load function definition
