pom.xml
As of issue #22, there are several `asm*` artifacts that don't have the same version. This might lead to compatibility issues as there are dependencies between those artifacts.
=> Unify asm versions

src/main/java/com/xceptance/xlt/common/XltConstants.java, src/main/java/com/xceptance/xlt/mastercontroller/ResultDownloader.java, src/main/java/com/xceptance/xlt/mastercontroller/TestLoadProfileConfiguration.java, src/main/java/com/xceptance/xlt/report/ReportGenerator.java, src/test/java/com/xceptance/xlt/mastercontroller/TestLoadProfileConfiguration_RampUpOffsetTest.java
* moved method to compute the total ramp-up period from ReportGenerator to LoadTestProfileConfiguration
* moved test case ReportGenerator_RampUpOffsetTest to LoadTestProfileConfiguration_RampUpOffsetTest and adjusted it accordingly
* have the ResultsDownloader write the total ramp-up time to the test properties file
* simplified ResultsDownloader a bit
=> #105: Write total ramp-up period to the results

config/testreport/js/xlt.js, config/xsl/loadreport/sections/agents.xsl, config/xsl/loadreport/text/descriptions.xsl, src/main/java/com/xceptance/xlt/report/providers/AbstractDataProcessor.java, src/main/java/com/xceptance/xlt/report/providers/AgentDataProcessor.java, src/main/java/com/xceptance/xlt/report/providers/AgentReport.java, src/main/java/com/xceptance/xlt/report/providers/AgentsReportProvider.java
- provide transaction count and error count as part of the agent data
- added new columns to the agent table displaying transaction count, error count, and error percentage per agent
=> #119: Add transaction errors to "Agents" report page

src/main/java/com/xceptance/xlt/agentcontroller/AgentManagerImpl.java, src/main/java/com/xceptance/xlt/agentcontroller/TestResultAmount.java, src/main/java/com/xceptance/xlt/mastercontroller/FireAndForgetUI.java, src/main/java/com/xceptance/xlt/mastercontroller/Main.java, src/main/java/com/xceptance/xlt/mastercontroller/NonInteractiveUI.java, src/main/java/com/xceptance/xlt/mastercontroller/ResultDownloader.java
Implemented new option `--only-download` that can be used to restrict result download to the given data types (comma-separated list). Supported values are `logs`, `measurements` and `resultbrowsers`.
Example: `mastercontroller.sh -auto -embedded --only-download=measurements,logs`
=> #129: Option to configure download result amount in non-interactive mode

config/testreport/js/xlt.js
CSS selector adjustments to target our own filter input only when syncing and/or (re)focusing and custom input fields stay untouched.
=> GH #162: Filtering capability in report syncs unrelated input fields

src/main/java/com/xceptance/xlt/engine/resultbrowser/DomUtils.java
Uses a more efficient attribute html encoding #159
=> Use a faster and more efficent attribute encoding lib

src/main/java/com/xceptance/xlt/engine/htmlunit/okhttp3/CookieJarImpl.java
- reuse logic from OkHttp to decide whether a cookie is to be sent back to a certain server
- handle host/wildcard domains consistently when converting cookies from/to HtmlUnit
=> #137: Improve cookie selection for OkHttp-based web connection

src/main/java/com/xceptance/xlt/engine/resultbrowser/assets/js/resultbrowser.js
Also feed the json viewer if the mime type indicates json-ish content, i.e. accept not only "application/json", but also "application/<...>+json".
=> #166: Result Browser does not show JSON view for content type application/vnd.api+json

ant-scripts/test.xml, src/test/java/com/xceptance/xlt/engine/OkHttpRequestBodyEncodingTest.java
Reworked test case to use a Jetty server instead of an Apache server.
=> #175: Fix test case OkHttpRequestBodyEncodingTest

samples/testsuite-performance/config/default.properties, samples/testsuite-posters/config/default.properties, samples/testsuite-showcases/config/default.properties, samples/testsuite-template/config/default.properties, samples/testsuite-xlt/config/default.properties, src/main/java/com/xceptance/xlt/clientperformance/PerformanceDataTransformator.java, src/main/java/com/xceptance/xlt/engine/SessionImpl.java, src/main/java/com/xceptance/xlt/engine/XltHttpWebConnection.java, src/main/java/com/xceptance/xlt/engine/resultbrowser/DumpMgr.java, src/main/java/com/xceptance/xlt/engine/resultbrowser/PageDOMClone.java, src/main/java/com/xceptance/xlt/engine/resultbrowser/PageTransformer.java, src/main/java/com/xceptance/xlt/engine/util/URLCleaner.java, src/main/java/com/xceptance/xlt/engine/util/UrlUtils.java, src/test/java/com/xceptance/xlt/engine/util/UrlUtilsTest.java
- introduce new property to control whether or not to remove user-info from request URL
- remove user-info from request URL if need to do so before writing timer data to CSV
- added tests for new method 'removeUserInfo' of utility class 'com.xceptance.xlt.engine.util.UrlUtils'
- added documentation of new property to all 'default.properties' files in sample test suites
=> 57: Hide credentials passed in the URL in the load test report

src/main/java/com/xceptance/xlt/agentcontroller/FileManagerServlet.java
- add content length header manually as the servlet API method allows int values only
=> #208: "Unexpected end of ZLIB input stream" error when downloading results

src/main/java/com/xceptance/xlt/api/webdriver/XltChromeDriver.java, src/main/java/com/xceptance/xlt/api/webdriver/XltFirefoxDriver.java
Changes:
- adjusted `XltFirefoxDriver` and `XltChromeDriver` to cast value of DriverService's 'environment' field java.util.Map instead of com.google.common.collect.ImmutableMap
Fixes #213
=> GH #213: ClassCastException while trying to use XLT's client-performane webdriver in screenless mode

bin/agent.cmd, bin/agent.sh, src/main/java/com/xceptance/xlt/agentcontroller/AgentControllerImpl.java, src/main/java/com/xceptance/xlt/common/XltConstants.java
Extended property `log4j2.configurationFile` to look for log4j2.yaml, log4j2.json, and log4j2.xml as well.
=> #240: Support alternative logger configuration file formats

resultbrowser/src/css/default.css, resultbrowser/src/index.html, resultbrowser/src/js/resultbrowser.js
- ensure content does not overflow (both in the left-side menu, but also in the content area)
- ensure the whole load error box is hidden, not just its content, if there was no load error
- ensure the splitter bar does not shrink when resizing the window
- make the splitter bar wider by 1 px so it is easier to grab
- ensure the View as HAR link is hidden also on network error/if not found on local disk
=> #260: Action/request menu in result browser shows no scrollbar, but overflows

config/xsl/loadreport/util/timer-section.xsl
While I appreciate this as a learning experience I wonder whether the change will be useful for load testers. I understand that it might be valuable for non-tech users to see the overview graphic first, but for evaluating the report I usually need the data tables more often.
=> #291: move summary chart above data tables

resultbrowser/package-lock.json, resultbrowser/package.json
Changes:
- updated development dependencies to latest
- dropped 'jquery' and 'lodash' as they are not used
- added override for 'inline-source' to enforce latest version
- replaced deprecated and unmaintained module 'http-serve' with 'http-server'
Closes #318.
=> Update dependencies used to bundle XLT ResultBrowser

resultbrowser/package.json
Removed quotes from argument of '--public-url' option passed to parcel.
Fixes #331
=> GH #331: Bundling the result browser fails on Windows

ant-scripts/test.xml, ant-scripts/timerrecorder.xml, ant-scripts/timerrecorder_chrome.xml, build.xml, pom.xml
Changes:
- drop build dependency 'ant-contrib'
- remove or replace usages of 'script' and 'scriptdef' tasks
- added required arguments to forked JVM when running tests in order to workaround JPMS issues
Solves #351
=> GH#351: Remove or replace JS stuff in Ant build scripts

config/testreport/js/xlt.js, config/xsl/loadreport/sections/agents.xsl, config/xsl/loadreport/util/timer-section.xsl
Added "overview" class to the overview sections before the tables on all relevant pages and made the filter ignore all sections with this class.
=> 375 dont filter out overview charts

src/main/java/com/xceptance/xlt/agentcontroller/AgentImpl.java
Terminate all descendant processes first before terminating the agent process itself (descends would get a new parent otherwise).
Closes #149
=> GH #149: When killing an agent kill the whole process tree

config/xsl/loadreport/util/timer-summary-row.xsl
Fixed the timer table summary row template to show the correct values for request data tables. Note that there is no (meaningful) value available for the overall number of distinct URLs, so the respective table footer cell is empty.
=> #392: Incorrect sum for Distinct and 1/s and 1/h request count

build.properties, config/mastercontroller.properties, src/main/java/com/xceptance/common/io/IoActionHandler.java, src/main/java/com/xceptance/xlt/agent/AgentMain.java, src/main/java/com/xceptance/xlt/agentcontroller/AgentControllerProxy.java, src/main/java/com/xceptance/xlt/agentcontroller/FileManagerProxy.java, src/main/java/com/xceptance/xlt/agentcontroller/FileManagerServlet.java, src/main/java/com/xceptance/xlt/agentcontroller/PartialGetUtils.java, src/main/java/com/xceptance/xlt/mastercontroller/MasterControllerConfiguration.java, src/main/java/com/xceptance/xlt/mastercontroller/MasterControllerMain.java, src/test/java/com/xceptance/xlt/agentcontroller/PartialGetUtils_ContentRangeHeaderTest.java, src/test/java/com/xceptance/xlt/agentcontroller/PartialGetUtils_RangeHeaderTest.java
- Use a series of partial GETs to download an archive file in chunks.
- Fall back to a full download in case the agent controller does not support chunked download yet.
- Retry downloading a file (chunk) in case of I/O errors.
- Made chunk size and download attempts per chunk configurable.
- Changed name of Chromium binary from "chromium-browser" to "chromium".
=> #400: Implement chunked downloads of results

config/testreport/css/default.css
* use a larger font size for "infinity" cells, however, without increasing the height of the table cell
* give "infinity" cells the same lighter shading as regular value cells when hovering over the respective table row
=> #415: Comparison Report: Issues with "infinity" cells

pom.xml
Update Guava to latest available version to fix vulnerabilities when working with temporary files in Guava v31.1-jre.
=> Upgrade guava from 31.1-jre to 32.1.2-jre

samples/testsuite-performance/config/default.properties, samples/testsuite-posters/config/default.properties, samples/testsuite-showcases/config/default.properties, samples/testsuite-template/config/default.properties, samples/testsuite-xlt/config/default.properties, src/main/java/com/xceptance/xlt/api/actions/AbstractHtmlPageAction.java, src/main/java/com/xceptance/xlt/engine/XltWebClient.java, src/main/java/com/xceptance/xlt/engine/scripting/htmlunit/ElementFinder.java, src/main/java/com/xceptance/xlt/engine/scripting/htmlunit/HtmlUnitCommandAdapter.java, src/test/java/com/xceptance/xlt/api/actions/AbstractHtmlPageActionTest.java, src/test/java/com/xceptance/xlt/engine/BaseUrlHandleTest.java, src/test/java/com/xceptance/xlt/engine/XltWebClientLoadStaticContentTest.java, src/test/java/com/xceptance/xlt/engine/scripting/webdriver/WebDriverUtilsTest.java, src/test/java/com/xceptance/xlt/engine/xltdriver/_2897_ClickOnDisabledElementTest.java, src/test/java/org/htmlunit/_1983_IFrameLoadTest.java, src/test/java/org/htmlunit/_2144_FileInputHasNonZeroWidthTest.java
JS engine is off by default and not started. A short test has shown that the scripts for regular load tests still work. We are also not creating the debugger object, if not needed.
-10 %
-200 MB
=> 423 disable js engine

src/main/java/com/xceptance/xlt/report/mergerules/AbstractPatternRequestFilter.java
Added to the previous change to improve processing by avoiding memory copies of the Matchresult as well as reusing the Matcher. Memory demand is about 250 to 400 MB less while processing.
Test results:
* 7.2 on a large customer data set: 05:04 (mm:ss)
* Merge #421: 04:02
* Improved memory handling and caching: 03:55
Not much but measurable.
=> 430 matchresult caching

resultbrowser/src/js/json-tree.js
Attach event handlers only if there is a valid JSON tree.
=> #436: Result Browser: Cannot view request details

src/main/java/com/xceptance/xlt/engine/socket/InstrumentedSocketImpl.java, src/main/java/com/xceptance/xlt/engine/socket/InstrumentedSocketImplFactory.java, src/main/java/com/xceptance/xlt/engine/socket/XltSockets.java
XLT does no longer throw if the socket layer cannot be instrumented with the used JVM, but logs a warning only.
=> #179: Support for JDK 17+

build.properties, config/reportgenerator.properties, src/main/java/com/xceptance/xlt/common/XltPropertyNames.java, src/main/java/com/xceptance/xlt/report/ReportGeneratorConfiguration.java, src/main/java/com/xceptance/xlt/report/providers/ErrorsReportProvider.java
limited the number of error traces and made them randomly replaced by later error traces, made amount and replacement chance into XLT properties
=> 295 limit the number of error traces per error type to 10 by default and sample the selection better

ant-scripts/timerrecorder_chrome.xml, src/main/java/com/xceptance/xlt/api/webdriver/XltChromeDriver.java, src/main/java/com/xceptance/xlt/clientperformance/WebExtConnectionHandler.java, xlt-timerrecorder-chrome/src/background.js, xlt-timerrecorder-chrome/src/manifest.json
Chrome Timer Recorder
* brought Manifest v3 code back
* upped minimum chrome version to 116 (see https://developer.chrome.com/docs/extensions/mv3/service_workers/service-worker-lifecycle/#chrome-116)
* installed a periodic task that sends a dummy message to XLT to keep the service worker alive
* made the usage of the session storage configurable (off by default)
* added a helper function to calculate the size of the request line
* minor optimizations
* added some useful logger functions
XLT
* made the usage of the session storage in the chrome timer recorder configurable (off by default)
* handle new keep-alive messages by ignoring them
* adjusted logging when receiving timer data
=> #390: Issues with the new timer recorder plugin for Chrome

config/testreport/css/default.css, config/xsl/diffreport/util/timer-cell.xsl
* removed any color info from the `infinity` CSS class
* added the correct color class to infinity cells instead
* additionally fixed the cell background for the `a0` class to be the standard gray background
=> #491: Diff Report: Sometimes wrong color used for infinity cells

config/reportgenerator.properties, src/main/java/com/xceptance/xlt/common/XltPropertyNames.java, src/main/java/com/xceptance/xlt/report/ReportGeneratorConfiguration.java, src/main/java/com/xceptance/xlt/report/providers/ErrorsReportProvider.java
The ideal state would be that only the [n] most common errors are saved complete with their stacktrace, but this can't be determinded at the time of saving, so let's put this in a followup issue in case we find a solution at some point, otherwise this will be sufficient to be able to avoid memory problems at report creation.
=> 439 stacktrace limiter

src/main/java/com/xceptance/xlt/engine/resultbrowser/ErrorCounter.java
Changes:
- create Timer thread as daemon thread such that VM can shutdown when all user threads have terminated
Closes #501.
=> GH #501: ErrorCounter timer thread prevents JVM to exit

src/main/java/com/xceptance/xlt/engine/DataManagerImpl.java, src/main/java/com/xceptance/xlt/engine/SessionImpl.java, src/test/java/com/xceptance/xlt/agent/DataRecordLoggingTest.java, src/test/java/com/xceptance/xlt/engine/DataManagerImplTest.java
Changes:
- invoke 'Metrics.getInstance()' as late as possible such that session is properly initialized (esp. its 'loadTest' flag)
- fix broken unit tests
Closes #502
=> GH 502: Real-time metrics reporting stopped working in XLT 7.0.0

src/main/java/com/xceptance/xlt/report/DataParserThread.java, src/main/java/com/xceptance/xlt/report/ReportGeneratorConfiguration.java
Get request processing rules already in the constructor. This way, any exception in this area causes the report generator to quit properly.
=> #524: Invalid merge rules cause the report generator to hang

src/main/java/com/xceptance/xlt/engine/XltWebClient.java, src/test/java/com/xceptance/xlt/engine/XltWebClientTest.java
When resetting the Web client, make sure the JavaScript engine and Web connection are recreated using XLT classes.
=> #535: No measurements after resetting the web client

resultbrowser/package-lock.json, resultbrowser/package.json
Changing to `inline-source --compress false` for index does the trick, file goes from 47.6KB (`--compress true`) to 49.8KB.
=> small npm vulnerability fixes + fix for missing css data after inlining

src/main/java/com/xceptance/common/net/HttpHeaderConstants.java, src/main/java/com/xceptance/xlt/engine/CachingHttpWebConnection.java, src/test/java/com/xceptance/xlt/engine/CachingHttpWebConnectionTest.java
* cache responses even if they are marked with "no-cache" or are already expired (they will be revalidated before next use)
* fixed calculation of expiration time
* adjusted test cases accordingly
=> #543: Fix caching and revalidation of expired resources

config/testreport/js/xlt.js
Fixed the issue where quickly clicking multiple times on a sortable header row might end up with an endless loop.
=> #551: Fixed hashupdate issue which results sometimes in an endless loop.

ant-scripts/sigtest.xml
* run sigtest as forked JVM to overcome issues with newer Ant versions
* updated sigtest library for better compatibility with Java 21 (target "sigsetup" works again)
=> #572: API signature validation fails when run with Ant v1.10.14+ and Java21
